// <auto-generated />
using System;
using InvestFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestFlow.Infrastructure.Persistence.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerAppDbContext))]
    partial class SqlServerAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestFlow.Domain.Entities.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoAtual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_Ativos_Ticker");

                    b.ToTable("Ativos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Petrobras PN",
                            PrecoAtual = 38.1200m,
                            Ticker = "PETR4",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vale ON",
                            PrecoAtual = 61.4500m,
                            Ticker = "VALE3",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            CriadoEm = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "CSHG Logística FII",
                            PrecoAtual = 162.3500m,
                            Ticker = "HGLG11",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 4,
                            CriadoEm = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Tesouro IPCA+ 2035",
                            PrecoAtual = 2150.7800m,
                            Ticker = "IPCA2035",
                            Tipo = 3
                        },
                        new
                        {
                            Id = 5,
                            CriadoEm = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Mini Índice Futuro Dez/26",
                            PrecoAtual = 131250.0000m,
                            Ticker = "WINZ26",
                            Tipo = 4
                        });
                });

            modelBuilder.Entity("InvestFlow.Domain.Entities.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lado")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoExecucao")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId")
                        .HasDatabaseName("IX_Ordens_AtivoId");

                    b.HasIndex("DataExecucao", "Status")
                        .HasDatabaseName("IX_Ordens_DataExecucao_Status");

                    b.ToTable("Ordens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 1, 4, 10, 17, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 38.3487m,
                            Quantidade = 200,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 1, 6, 10, 34, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.5114m,
                            Quantidade = 300,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 1, 8, 10, 51, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 161.7006m,
                            Quantidade = 40,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 1, 10, 11, 8, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2131.4230m,
                            Quantidade = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 1, 12, 11, 25, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 132168.7500m,
                            Quantidade = 6,
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 1, 14, 11, 42, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 38.1962m,
                            Quantidade = 700,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 1, 16, 11, 59, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.2656m,
                            Quantidade = 100,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 1, 18, 12, 16, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 161.0512m,
                            Quantidade = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 1, 20, 12, 33, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 2167.9862m,
                            Quantidade = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 10,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 1, 22, 12, 50, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 131643.7500m,
                            Quantidade = 4,
                            Status = 3
                        },
                        new
                        {
                            Id = 11,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 1, 24, 13, 7, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 38.0438m,
                            Quantidade = 500,
                            Status = 2
                        },
                        new
                        {
                            Id = 12,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 1, 26, 13, 24, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 61.0198m,
                            Quantidade = 600,
                            Status = 2
                        },
                        new
                        {
                            Id = 13,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 1, 28, 13, 41, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 163.8112m,
                            Quantidade = 70,
                            Status = 2
                        },
                        new
                        {
                            Id = 14,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 1, 30, 13, 58, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2159.3831m,
                            Quantidade = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 2, 1, 14, 15, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 131118.7500m,
                            Quantidade = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 16,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 2, 3, 14, 32, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 37.8913m,
                            Quantidade = 300,
                            Status = 2
                        },
                        new
                        {
                            Id = 17,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 2, 5, 14, 49, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 62.0645m,
                            Quantidade = 400,
                            Status = 2
                        },
                        new
                        {
                            Id = 18,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 2, 7, 15, 6, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 163.1618m,
                            Quantidade = 50,
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 2, 9, 15, 23, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2150.7800m,
                            Quantidade = 6,
                            Status = 2
                        },
                        new
                        {
                            Id = 20,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 2, 11, 15, 40, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 130593.7500m,
                            Quantidade = 7,
                            Status = 3
                        },
                        new
                        {
                            Id = 21,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 2, 13, 15, 57, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 37.7388m,
                            Quantidade = 100,
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 2, 15, 16, 14, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.8187m,
                            Quantidade = 200,
                            Status = 2
                        },
                        new
                        {
                            Id = 23,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 2, 17, 16, 31, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 162.5124m,
                            Quantidade = 30,
                            Status = 2
                        },
                        new
                        {
                            Id = 24,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 2, 19, 16, 48, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 2142.1769m,
                            Quantidade = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 25,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 2, 21, 17, 5, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 130068.7500m,
                            Quantidade = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 26,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 2, 23, 17, 22, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 38.3868m,
                            Quantidade = 600,
                            Status = 2
                        },
                        new
                        {
                            Id = 27,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 2, 25, 17, 39, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 61.5729m,
                            Quantidade = 700,
                            Status = 2
                        },
                        new
                        {
                            Id = 28,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 2, 27, 17, 56, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 161.8630m,
                            Quantidade = 10,
                            Status = 2
                        },
                        new
                        {
                            Id = 29,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 3, 1, 18, 13, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2133.5738m,
                            Quantidade = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 30,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 3, 3, 18, 30, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 132300.0000m,
                            Quantidade = 3,
                            Status = 3
                        },
                        new
                        {
                            Id = 31,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 3, 5, 18, 47, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 38.2344m,
                            Quantidade = 400,
                            Status = 2
                        },
                        new
                        {
                            Id = 32,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 3, 7, 19, 4, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.3271m,
                            Quantidade = 500,
                            Status = 2
                        },
                        new
                        {
                            Id = 33,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 3, 9, 19, 21, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 161.2136m,
                            Quantidade = 60,
                            Status = 2
                        },
                        new
                        {
                            Id = 34,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 3, 11, 19, 38, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2170.1370m,
                            Quantidade = 7,
                            Status = 2
                        },
                        new
                        {
                            Id = 35,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 3, 13, 19, 55, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 131775.0000m,
                            Quantidade = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 36,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 3, 15, 20, 12, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 38.0819m,
                            Quantidade = 200,
                            Status = 2
                        },
                        new
                        {
                            Id = 37,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 3, 17, 20, 29, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.0813m,
                            Quantidade = 300,
                            Status = 2
                        },
                        new
                        {
                            Id = 38,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 3, 19, 20, 46, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 163.9735m,
                            Quantidade = 40,
                            Status = 2
                        },
                        new
                        {
                            Id = 39,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 3, 21, 21, 3, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 2161.5339m,
                            Quantidade = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 40,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 3, 23, 21, 20, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 131250.0000m,
                            Quantidade = 6,
                            Status = 3
                        },
                        new
                        {
                            Id = 41,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 3, 25, 21, 37, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 37.9294m,
                            Quantidade = 700,
                            Status = 2
                        },
                        new
                        {
                            Id = 42,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 3, 27, 21, 54, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 60.8355m,
                            Quantidade = 100,
                            Status = 2
                        },
                        new
                        {
                            Id = 43,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 3, 29, 22, 11, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 163.3241m,
                            Quantidade = 20,
                            Status = 2
                        },
                        new
                        {
                            Id = 44,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 3, 31, 22, 28, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2152.9308m,
                            Quantidade = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 45,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 4, 2, 22, 45, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 130725.0000m,
                            Quantidade = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 46,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 4, 4, 23, 2, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 37.7769m,
                            Quantidade = 500,
                            Status = 2
                        },
                        new
                        {
                            Id = 47,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 4, 6, 23, 19, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.8802m,
                            Quantidade = 600,
                            Status = 2
                        },
                        new
                        {
                            Id = 48,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 4, 8, 23, 36, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 162.6747m,
                            Quantidade = 70,
                            Status = 2
                        },
                        new
                        {
                            Id = 49,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 4, 10, 23, 53, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2144.3277m,
                            Quantidade = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 50,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 4, 13, 0, 10, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 130200.0000m,
                            Quantidade = 2,
                            Status = 3
                        },
                        new
                        {
                            Id = 51,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 4, 15, 0, 27, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 38.4250m,
                            Quantidade = 300,
                            Status = 1
                        },
                        new
                        {
                            Id = 52,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 4, 17, 0, 44, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 61.6344m,
                            Quantidade = 400,
                            Status = 1
                        },
                        new
                        {
                            Id = 53,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 4, 19, 1, 1, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 162.0253m,
                            Quantidade = 50,
                            Status = 1
                        },
                        new
                        {
                            Id = 54,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 4, 21, 1, 18, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 2135.7245m,
                            Quantidade = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 55,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 4, 23, 1, 35, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 132431.2500m,
                            Quantidade = 7,
                            Status = 1
                        },
                        new
                        {
                            Id = 56,
                            AtivoId = 1,
                            DataExecucao = new DateTime(2026, 4, 25, 1, 52, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 38.2725m,
                            Quantidade = 100,
                            Status = 1
                        },
                        new
                        {
                            Id = 57,
                            AtivoId = 2,
                            DataExecucao = new DateTime(2026, 4, 27, 2, 9, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 61.3886m,
                            Quantidade = 200,
                            Status = 1
                        },
                        new
                        {
                            Id = 58,
                            AtivoId = 3,
                            DataExecucao = new DateTime(2026, 4, 29, 2, 26, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 161.3759m,
                            Quantidade = 30,
                            Status = 1
                        },
                        new
                        {
                            Id = 59,
                            AtivoId = 4,
                            DataExecucao = new DateTime(2026, 5, 1, 2, 43, 0, 0, DateTimeKind.Utc),
                            Lado = 1,
                            PrecoExecucao = 2172.2878m,
                            Quantidade = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 60,
                            AtivoId = 5,
                            DataExecucao = new DateTime(2026, 5, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            Lado = 2,
                            PrecoExecucao = 131906.2500m,
                            Quantidade = 5,
                            Status = 3
                        });
                });

            modelBuilder.Entity("InvestFlow.Domain.Entities.Ordem", b =>
                {
                    b.HasOne("InvestFlow.Domain.Entities.Ativo", "Ativo")
                        .WithMany("Ordens")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("InvestFlow.Domain.Entities.Ativo", b =>
                {
                    b.Navigation("Ordens");
                });
#pragma warning restore 612, 618
        }
    }
}
